name: Pull Request

on:
  pull_request:
    branches:
      - '*'
    types:
      [
        opened,
        reopened,
        synchronize,
        edited,
        ready_for_review,
        unassigned,
        assigned,
      ]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Setup Node.js to run tests
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run tests with Jest
        run: npm test

  dependabot:
    name: Dependabot
    runs-on: ubuntu-latest
    needs: test
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Auto-merge PR of Dependabot
        run: gh pr merge --auto --merge "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
